-- Database schema for rooms and applications
CREATE TABLE Room (
  id VARCHAR(36) PRIMARY KEY DEFAULT UUID(),
  roomNumber VARCHAR(10) UNIQUE NOT NULL,
  status ENUM('OCCUPIED', 'VACANT') DEFAULT 'VACANT',
  price DECIMAL(10,2) NOT NULL,
  size INT NOT NULL,
  bedrooms INT NOT NULL DEFAULT 1,
  bathrooms INT NOT NULL DEFAULT 1,
  hasWifi BOOLEAN DEFAULT TRUE,
  hasParking BOOLEAN DEFAULT FALSE,
  hasWater BOOLEAN DEFAULT TRUE,
  description TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE RoomImage (
  id VARCHAR(36) PRIMARY KEY DEFAULT UUID(),
  roomId VARCHAR(36) NOT NULL,
  url VARCHAR(500) NOT NULL,
  isPrimary BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (roomId) REFERENCES Room(id) ON DELETE CASCADE
);

CREATE TABLE Application (
  id VARCHAR(36) PRIMARY KEY DEFAULT UUID(),
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(20) NOT NULL,
  message TEXT NOT NULL,
  roomId VARCHAR(36) NOT NULL,
  status ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (roomId) REFERENCES Room(id)
);