import type { Metadata } from "next";
import { AuthProvider } from "./context/AuthContext";
 
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const maintenanceMode = false

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Titans Rental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (maintenanceMode) {
    return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <div className="flex items-center justify-center ">
            <p className="  font-bold">Server suspended by the owner</p>
          </div>
        </body>
      </html>
    );
  }

  return (
     <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
        <Navbar />
        {children}
        <Footer />
        </AuthProvider>

      </body>
    </html>
   );
}
